DROP TABLE attributes_table CASCADE;
DROP TABLE business_table CASCADE;
DROP TABLE categories_table CASCADE;
DROP TABLE checkins_table CASCADE;
DROP TABLE friends_table CASCADE;
DROP TABLE hours_table CASCADE;
DROP TABLE tip_table CASCADE;
DROP TABLE users_table CASCADE;
DROP TABLE day_table CASCADE;